/** Library: the bookshelf at /library. Covers are the editions logged on
 * Goodreads (Amazon's hi-res image where it's the same cover, else Goodreads'
 * own ~300px one), ≤640px q84 WebP in public/library/covers/; originals in
 * media-originals/library/en/. Reviews are from Goodreads, lightly trimmed. */

export const TAGS = {
  italian: "Italian lit",
  japanese: "Japanese lit",
  russian: "Russian lit",
  german: "German lit",
  taiwanese: "Taiwanese lit",
  novel: "Novel",
  novella: "Novella",
  memoir: "Memoir",
  essay: "Essay",
  nonfiction: "Nonfiction",
  history: "History",
  philosophy: "Philosophy",
  aesthetics: "Aesthetics",
  design: "Design",
  tea: "Tea",
  spirituality: "Spirituality",
  classic: "Classic",
  friendship: "Female friendship",
  comingOfAge: "Coming of age",
  love: "Love",
  grief: "Grief",
  medicine: "Medicine",
  madness: "Madness",
  queer: "Queer",
  sciFi: "Sci-fi",
  experimental: "Experimental",
  myth: "Mythology",
  family: "Family",
  immigration: "Immigration",
  china: "China",
  tech: "Technology",
  war: "War",
  french: "French lit",
  korean: "Korean lit",
  british: "British lit",
  american: "American lit",
  canadian: "Canadian lit",
  shortStories: "Short stories",
  autofiction: "Autofiction",
  gothic: "Gothic",
  surreal: "Magical realism",
  friends: "Friendship",
  psychology: "Psychology",
  writing: "Writing",
  art: "Art",
  trueCrime: "True crime",
} as const;

export type TagKey = keyof typeof TAGS;

export type Book = {
  slug: string;
  title: string;
  author: string;
  /** Original publication year. */
  year: number;
  /** Month finished, "YYYY-MM". */
  read?: string;
  rating?: 1 | 2 | 3 | 4 | 5;
  /** A colour pulled from the cover, for tints and the colour-sorted shelf. */
  tone: string;
  tags: TagKey[];
  /** Empty until written (shows "Review coming soon"). */
  review: string[];
};

export const cover = (b: Book) => `/library/covers/${b.slug}.webp`;

export const books: Book[] = [
  {
    slug: "book-of-tea",
    title: "The Book of Tea",
    author: "Kakuzō Okakura",
    year: 1906,
    read: "2024-06",
    rating: 4,
    tone: "#6f7a2c",
    tags: ["japanese", "essay", "tea", "philosophy"],
    review: [
      "i sympathize heavily with okakura’s mission",
    ],
  },
  {
    slug: "in-praise-of-shadows",
    title: "In Praise of Shadows",
    author: "Jun'ichirō Tanizaki",
    year: 1933,
    read: "2024-09",
    rating: 5,
    tone: "#2a2a2a",
    tags: ["japanese", "essay", "aesthetics"],
    review: ["i would love to sit and chat with this man over tea. he’s just like me"],
  },
  {
    slug: "siddhartha",
    title: "Siddhartha",
    author: "Hermann Hesse",
    year: 1922,
    read: "2024-05",
    rating: 4,
    tone: "#d07a2a",
    tags: ["german", "novella", "spirituality"],
    review: [
      "after letting my notes on this book marinate, one year later i have returned feeling much more “childlike,” as siddhartha puts it.",
      "the self, personal growth, and life is cyclic. nothing is linear. the young are arrogant and don’t know things. nobody can teach you how to attain spiritual peace or to gain enlightenment; only your lived experiences can help you reach this state.",
    ],
  },
  {
    slug: "days-of-abandonment",
    title: "The Days of Abandonment",
    author: "Elena Ferrante",
    year: 2002,
    read: "2024-09",
    rating: 5,
    tone: "#5a5aa8",
    tags: ["italian", "novel", "madness"],
    review: [
      "ferrante never ceases to amaze me. once again her writing has put a spell on me. while reading this, i was lost in the chaos of olga's demise, just drowning in her insanity. i was crawling on the floor, losing my mind with her.",
      "kind of like the yellow wallpaper but 100x better. incredible reading experience. incredible book. incredible title. what am i going to do when i run out of ferrante books to read",
    ],
  },
  {
    slug: "being-mortal",
    title: "Being Mortal",
    author: "Atul Gawande",
    year: 2014,
    read: "2023-11",
    rating: 5,
    tone: "#6b8a3a",
    tags: ["nonfiction", "medicine", "grief"],
    review: ["as someone who is about to face profound grief, this book made me cry"],
  },
  {
    slug: "new-name",
    title: "The Story of a New Name",
    author: "Elena Ferrante",
    year: 2012,
    read: "2023-10",
    rating: 5,
    tone: "#8ab0b8",
    tags: ["italian", "novel", "friendship", "comingOfAge"],
    review: [
      "significantly better than my brilliant friend, which i already treated with high esteem… elena ferrante, the woman that you are",
    ],
  },
  {
    slug: "brothers-karamazov",
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    year: 1880,
    read: "2025-10",
    rating: 5,
    tone: "#b8261e",
    tags: ["russian", "novel", "classic", "philosophy"],
    review: [
      "the heart of this novel is so overshadowed by the dramatic murder trial and grandiose intellectual monologues that i almost forget its most revolutionary moments, like alyosha’s kiss to ivan after the grand inquisitor speech.",
      "i think of how much dostoevsky’s personal suffering and philosophy has been imbued into these pages, and how beautiful that, in some ways, his solution to grief was to reinvent his deceased baby son into the angel and hero of this novel, the messenger that delivers dostoevsky’s core philosophy of active love and compassion…",
    ],
  },
  {
    slug: "wabi-sabi",
    title: "Wabi-Sabi: for Artists, Designers, Poets & Philosophers",
    author: "Leonard Koren",
    year: 1994,
    read: "2022-08",
    rating: 4,
    tone: "#8a6a3a",
    tags: ["aesthetics", "design", "philosophy"],
    review: [
      "reading this again 4 years later with a much stronger grasp on japanese philosophy and spirituality... i really enjoyed this!",
      "i like how koren organized the book through sections on 1) metaphysics, 2) spiritual values, 3) state of mind, 4) moral precepts, and 5) material qualities, and that he set up binaries contrasting wabi-sabi with other schools of thought like modernism. … but, the photographs did very little work reinforcing those concepts, and i wish koren had included more robust analysis of his wabi-sabi examples.",
      "however, the actual subject matter was right up my alley... i learned about iemoto families (which made me think: ah, so the Mansei-en bonsai garden from the 19th century is owned by what's called an iemoto family!). i also learned that japanese traditional arts are all interconnected … the tea ceremony was “an eclectic social art form combining... architecture, interior and garden design, flower arranging, painting, food preparation, and performance.” also also, the idea that one must bend or crawl in order to enter the wabi-sabi tea room as a symbolic act of humility - and that once completed, everyone in the tea room becomes of equal status - was fascinating.",
      "finally, i liked the footnote at the end warning readers to maybe not refer to japanese ideas and values as “eastern” … why shy away from the fact that eating hamburgers and listening to the beatles is incredibly japanese?",
    ],
  },
  {
    slug: "strange-weather-in-tokyo",
    title: "Strange Weather in Tokyo",
    author: "Hiromi Kawakami",
    year: 2001,
    read: "2022-07",
    rating: 5,
    tone: "#c8302a",
    tags: ["japanese", "novel", "love"],
    review: [
      "now on my bucket list: mushroom hunting, reminiscing over my schoolgirl youth at a cherry blossom watching party, and collecting littlenecked clams in a hot springs town by the sea with my lover at night…",
      "tsukiko is such an endearing, silly girl. truly, what a lovely girl you are, tsukiko",
    ],
  },
  {
    slug: "the-membranes",
    title: "The Membranes",
    author: "Chi Ta-wei",
    year: 1995,
    read: "2022-05",
    rating: 5,
    tone: "#d8702a",
    tags: ["taiwanese", "novel", "sciFi", "queer"],
    review: ["this is my favorite book of all time rn…obsessed"],
  },
  {
    slug: "fish-in-exile",
    title: "Fish in Exile",
    author: "Vi Khi Nao",
    year: 2016,
    read: "2022-06",
    rating: 4,
    tone: "#7a8a96",
    tags: ["novel", "experimental", "grief", "myth"],
    review: [
      "the poetic wounds of modern, mythological homer… defamiliarized language… the most beautiful, beautiful prose… intelligent in every way",
    ],
  },
  {
    slug: "rape-of-nanking",
    title: "The Rape of Nanking",
    author: "Iris Chang",
    year: 1997,
    read: "2020-12",
    rating: 5,
    tone: "#d8412e",
    tags: ["history", "china", "war"],
    review: ["how many times can a heart break? to nanjing, my first love."],
  },
  {
    slug: "the-unpassing",
    title: "The Unpassing",
    author: "Chia-Chia Lin",
    year: 2019,
    read: "2020-04",
    rating: 5,
    tone: "#2a4a6a",
    tags: ["novel", "family", "immigration", "grief"],
    review: [
      "yesterday my creative writ prof and i both gushed over this book… she said it’s an incredibly atmospheric novel that was made for people who love to read and write… we both love the unpassing…",
    ],
  },
  {
    slug: "notes-of-a-crocodile",
    title: "Notes of a Crocodile",
    author: "Qiu Miaojin",
    year: 1994,
    read: "2018-02",
    rating: 5,
    tone: "#e8b81a",
    tags: ["taiwanese", "novel", "queer", "comingOfAge"],
    review: ["i read this at such a formative age that this book is forever etched into my soul"],
  },
  {
    slug: "breakneck",
    title: "Breakneck: China's Quest to Engineer the Future",
    author: "Dan Wang",
    year: 2025,
    read: "2025-11",
    rating: 5,
    tone: "#c9a43a",
    tags: ["nonfiction", "china", "tech"],
    review: [
      "I've only really listened to podcasts discussing China's modern history as a technocratic state, but this week I finally got to sit down and read a proper thesis-driven publication about how this affects China's policy leadership and contrasts with the U.S.'s.",
      "According to Wang, China is an engineering state that can build public infrastructure at breakneck speed whereas the U.S. is a lawyerly society that is designed to block policy change. … Wang warns us that, while the U.S. has plenty of advantages over China on the global stage, China is the country that has the engineering smarts and manpower to build in an apocalyptic scenario...",
      "He conducts incredible deep dives into China's two most indebted regions, Guizhou and Tianjin … It's why we have Paris replicas in rural parts of China that fail to attract tourists and skyscraper buildings that have zero inhabitants.",
      "I also really appreciated Wang’s last chapter, which functioned partially as a personal memoir and gave context into his immigrant upbringing. Really timely and great read.",
    ],
  },
  {
    slug: "mountains-are-high",
    title: "The Mountains Are High",
    author: "Alec Ash",
    year: 2023,
    read: "2024-07",
    rating: 4,
    tone: "#d8a060",
    tags: ["memoir", "china"],
    review: [
      "before reading this, if you had told me that dali, a city in rural china, is a psychedelic rave haven that houses the kind of environmentalist collectives, coworking spaces, and web3 conferences that you'd find in SF or toronto...i would never have believed you.",
      "100% worth reading just to learn about the cultural landscape of this one (1) city... i’m really interested in the psychogeography of cities, and its historical role in safeguarding counterculture rebels who want to escape state surveillance and societal norms.",
    ],
  },
  {
    slug: "blockchain-chicken-farm",
    title: "Blockchain Chicken Farm",
    author: "Xiaowei Wang",
    year: 2020,
    read: "2022-08",
    rating: 5,
    tone: "#6a7a5a",
    tags: ["nonfiction", "china", "tech"],
    review: [
      "overwhelmingly good. took so many notes - all my fav topics (shanzhai, sinofuturism, urban-rural gap, neural networks, ethics in tech, etc).",
    ],
  },
  {
    slug: "sweet-days-of-discipline",
    title: "Sweet Days of Discipline",
    author: "Fleur Jaeggy",
    year: 1989,
    read: "2025-03",
    rating: 4,
    tone: "#7a8a7a",
    tags: ["italian", "novella", "comingOfAge"],
    review: [
      "sweet days of discipline is a hypnotic and rare find. set in postwar switzerland, we meet the fourteen-year-old narrator at a catholic all-girls boarding school. … when a new girl—frédérique—arrives, distant and obedient, the narrator tumbles into an obsessive mission to conquer her.",
      "i'm sensing a more subtle teetering between submission and dominion, one that exists on a spiritual plane rather than purely physical … the girls are chaste, but the energy is sexual (possessiveness, jealousy, etc.).",
      "what makes these days of discipline so sweet is this “senile girlhood” that eats at the boarders' vitality. being young and pretty is sweet, but being sheltered from the world during adolescence is saccharine.",
      "4.5 stars! i adored this book... so many beautiful lines pocketed forever: “There is no time, at that time. Childhood is ancient.”",
    ],
  },
  {
    slug: "how-to-know-a-person",
    title: "How to Know a Person",
    author: "David Brooks",
    year: 2023,
    read: "2024-01",
    rating: 5,
    tone: "#d8502a",
    tags: ["nonfiction", "psychology", "friends"],
    review: [
      "there are many times this book nearly made me cry, and i’m grateful that this was my first read of 2024. it was beautifully written, confessional, non-judgmental, and actionable. it felt like a spiritual massage, and somehow i felt seen?",
      "this was an inspiring book that revived the charm and spectacle of life for me. there is so much wonder to be found—in strangers, acquaintances, old friends, and new ones!! we are all mysteries and precious souls that long to be known, that long to be asked questions about who we are.",
      "my favorite lines from this book (among the probably 50 quotes sitting in my notes app): … “Respect is a gift you offer with your eyes.”",
    ],
  },
  {
    slug: "whale",
    title: "Whale",
    author: "Cheon Myeong-kwan",
    year: 2004,
    read: "2023-05",
    rating: 5,
    tone: "#3a4ab0",
    tags: ["korean", "novel", "surreal"],
    review: [
      "i simply could not put this down. i wish i could give this more than 5 stars. one of my all time favorites for sure",
    ],
  },
  {
    slug: "simple-passion",
    title: "Simple Passion",
    author: "Annie Ernaux",
    year: 1991,
    read: "2024-09",
    rating: 5,
    tone: "#2a3f9a",
    tags: ["french", "autofiction", "love"],
    review: [
      "my first annie ernaux. beautiful, vulnerable, intelligent, and self-aware. this book is exacting in its representation of all-consuming passion, i can attest to that... loved the last few pages especially, which marked it as a book that now feels so personal and special to me…",
      "“I measured time differently, with all my body. … Without knowing, he brought me closer to the world.”",
    ],
  },
  {
    slug: "madame-bovary",
    title: "Madame Bovary",
    author: "Gustave Flaubert",
    year: 1856,
    read: "2023-01",
    rating: 4,
    tone: "#b8a878",
    tags: ["french", "novel", "classic"],
    review: [
      "my favorite feral woman",
    ],
  },
  {
    slug: "stay-true",
    title: "Stay True",
    author: "Hua Hsu",
    year: 2022,
    read: "2023-03",
    rating: 5,
    tone: "#f07a30",
    tags: ["memoir", "friends", "grief"],
    review: [
      "oh… my heart",
      "i’m violently sympathetic to the writer’s commitment to deconstructing memory and revisiting the past. my creative writing professor once said that writers feel an exceptional awareness towards memory and emotion. … we are perpetually stuck in the past, unable to envision our multiple futures. and it’s true, hua hsu is just like me. he has been writing this tribute to the memory of his best friend for 20 years.",
      "this book is spilling with love, with hope, with tenderness in every way. … this is the sweetest, purest piece of writing on asian american male friendship to exist. an absolute must-read.",
    ],
  },
  {
    slug: "craft-in-the-real-world",
    title: "Craft in the Real World",
    author: "Matthew Salesses",
    year: 2021,
    read: "2022-10",
    rating: 5,
    tone: "#6a3fb0",
    tags: ["nonfiction", "writing"],
    review: [
      "man this guy is so great. this book is basically an exposé on the racist and imperialist origins of iowa writers’ workshop and a radical reimagining of how fiction writing workshops could be structured.",
      "anyways this book was brilliant, revolutionary, creative, and enlightening!",
    ],
  },
  {
    slug: "rebecca",
    title: "Rebecca",
    author: "Daphne du Maurier",
    year: 1938,
    read: "2024-09",
    rating: 5,
    tone: "#b5402a",
    tags: ["british", "gothic", "novel", "classic"],
    review: [
      "i eat up everything daphne du maurier writes. the perfect autumnal read",
    ],
  },
  {
    slug: "temporary",
    title: "Temporary",
    author: "Hilary Leichter",
    year: 2020,
    read: "2022-06",
    rating: 5,
    tone: "#e85a9a",
    tags: ["american", "novel", "surreal"],
    review: [
      "a whimsical book tumbling with creativity and wonder!! brilliant, unpredictable, emotional...a very, very special book if read all the way through <3",
    ],
  },
  {
    slug: "pure-colour",
    title: "Pure Colour",
    author: "Sheila Heti",
    year: 2022,
    read: "2022-03",
    rating: 5,
    tone: "#6aa83a",
    tags: ["canadian", "novel", "experimental"],
    review: [
      "4.5/5 sheila heti is a gem and i adore her mind",
    ],
  },
  {
    slug: "shanzhai",
    title: "Shanzhai: Deconstruction in Chinese",
    author: "Byung-Chul Han",
    year: 2011,
    read: "2021-07",
    rating: 5,
    tone: "#4848a8",
    tags: ["german", "philosophy", "china"],
    review: [
      "i still think about this book all the time",
    ],
  },
  {
    slug: "dept-of-speculation",
    title: "Dept. of Speculation",
    author: "Jenny Offill",
    year: 2014,
    read: "2021-06",
    rating: 5,
    tone: "#d85a50",
    tags: ["american", "novel", "love", "experimental"],
    review: [
      "this was such a lovely, hilarious, confessional, perceptive, complicated work of genius. i can’t express how much i adore it. offill is such an amazing writer. every line is perfect. everything. i basically took screenshots of every page. she writes emotion so well and i am sad now. :(",
    ],
  },
  {
    slug: "convenience-store-woman",
    title: "Convenience Store Woman",
    author: "Sayaka Murata",
    year: 2016,
    read: "2021-07",
    rating: 5,
    tone: "#f2d21a",
    tags: ["japanese", "novel"],
    review: [
      "i love her…",
    ],
  },
  {
    slug: "people-from-my-neighbourhood",
    title: "People From My Neighbourhood",
    author: "Hiromi Kawakami",
    year: 2016,
    read: "2022-06",
    rating: 5,
    tone: "#e8a8a0",
    tags: ["japanese", "shortStories", "surreal"],
    review: [
      "hilarious, charming, makes you feel like crawling into a peach and living there for a while. the kind of book i’d want to write",
    ],
  },
  {
    slug: "kafka-on-the-shore",
    title: "Kafka on the Shore",
    author: "Haruki Murakami",
    year: 2002,
    read: "2023-05",
    rating: 4,
    tone: "#c98a6a",
    tags: ["japanese", "novel", "surreal"],
    review: [
      "i’ve never read a book with such beautiful intertextuality. i love mr. nakata",
    ],
  },
  {
    slug: "on-the-origin-of-species",
    title: "On the Origin of Species and Other Stories",
    author: "Kim Bo-young",
    year: 2021,
    read: "2022-07",
    rating: 5,
    tone: "#2a2a2a",
    tags: ["korean", "shortStories", "sciFi"],
    review: [
      "bo-young kim, master of tackling the (post)human condition, you have transcended the anglophone world of science fiction that is polluted by too many -isms to count, and i have gladly joined your cult following. this was an incredible reading experience… shit",
    ],
  },
  {
    slug: "speculative-everything",
    title: "Speculative Everything",
    author: "Anthony Dunne & Fiona Raby",
    year: 2013,
    read: "2022-08",
    rating: 5,
    tone: "#3fbf5a",
    tags: ["design", "nonfiction"],
    review: [
      "this book was big in scope and complexity but i think what it does really well is convince me of the social weight of imagination… “there is no longer one reality, but seven billion different ones. the challenge is to give them form.”",
      "according to the authors, the role of the speculative designer is to be someone who uses the language of design to provoke, challenge, and tease out the imagined futures that the people want. it’s true… we should and can be designing for what this world could be…",
      "my favorite part was the moment on intentional communities (cults) as harbingers of materializing their own imagined micro-utopias into reality (aka proof you CAN manipulate reality into something that goes against the dominating social consciousness).",
    ],
  },
  {
    slug: "my-death",
    title: "My Death",
    author: "Lisa Tuttle",
    year: 2004,
    read: "2025-11",
    rating: 5,
    tone: "#b06a3a",
    tags: ["novella", "gothic", "art"],
    review: [
      "teetering between what?? huh??? and yes yes yes :o",
    ],
  },
  {
    slug: "the-art-thief",
    title: "The Art Thief",
    author: "Michael Finkel",
    year: 2023,
    read: "2025-07",
    rating: 5,
    tone: "#c8302a",
    tags: ["nonfiction", "trueCrime", "art"],
    review: [
      "ohhhh how decadent… oscar wilde would have understood you my friend",
    ],
  },
  {
    slug: "widow-basquiat",
    title: "Widow Basquiat",
    author: "Jennifer Clement",
    year: 2000,
    read: "2025-06",
    rating: 5,
    tone: "#e8c21a",
    tags: ["memoir", "art", "love"],
    review: [
      "absolutely blown away. so many things to love about this book :(",
      "for context, clement was close friends with suzanne, basquiat’s longtime lover, during the period that this book (which is about suzanne) was set. she did such great justice to the fragmented form. beautiful, poetic storytelling. … i was hooked and incredibly moved",
      "i really felt like i was there witnessing this cambrian explosion of artistic and sexual freedom. it was chaotic and beautiful and sadly ephemeral—destroyed by the aids epidemic. something so giovanni’s-room-tragic about this.",
      "thinking of the self-destructive artist figure we see so often in history. does being a creative genius curse you to a fate where you slowly destroy yourself in the name of being great? … to be immortalized in history as one of the greats, must there always be sacrifice involved??",
      "also, i love jennifer clement. she is an angel and she loves suzanne so much. … to be seen and understood is to be loved!!!! what a beautiful beautiful friendship!!!!",
    ],
  },
  {
    slug: "other-rivers",
    title: "Other Rivers: A Chinese Education",
    author: "Peter Hessler",
    year: 2024,
    read: "2026-05",
    rating: 5,
    tone: "#3a78c8",
    tags: ["memoir", "china"],
    review: [
      "4.5. really interesting deep dive on what it's like to not only raise middle-school-age children in the chinese public school system but also to teach journalism at a chinese university as a foreigner. … he has led a long legacy of conducting multidimensional, empathetic journalism on chinese society since the '90s and i really respect him for his contributions to the literature",
      "i found the phenomenon of “little pinks” - fiery nationalists in the young generation - interesting too, the idea that some freshmen might have reported hessler for his teaching content and nearly gotten him fired. the contrast between the betrayals of “little pinks” and the behavior of hessler's bright, passionate elective students, some of whom risked their lives to conduct research for their final papers … is quite interesting. also very timely notes on “involution” and “letting it rot.”",
    ],
  },
  {
    slug: "subplot",
    title: "The Subplot: What China Is Reading and Why It Matters",
    author: "Megan Walsh",
    year: 2022,
    read: "2023-01",
    rating: 5,
    tone: "#f2b53a",
    tags: ["nonfiction", "china", "writing"],
    review: ["i am the target audience. so so good"],
  },
  {
    slug: "pale-view-of-hills",
    title: "A Pale View of Hills",
    author: "Kazuo Ishiguro",
    year: 1982,
    read: "2025-11",
    rating: 4,
    tone: "#8f9a3c",
    tags: ["japanese", "novel", "family", "grief"],
    review: [
      "surprised that a book that is 80% dialogue can hold you at such distance and still leave you permanently changed. motherhood, grief, self-preservation, and the fallibility of memory—japanese literature at its finest",
    ],
  },
  {
    slug: "brilliant-friend",
    title: "My Brilliant Friend",
    author: "Elena Ferrante",
    year: 2011,
    read: "2023-07",
    rating: 4,
    tone: "#7d93a6",
    tags: ["italian", "novel", "friendship", "comingOfAge"],
    review: ["not sure what to say except that i highlighted like everything in this book"],
  },
  {
    slug: "breath-becomes-air",
    title: "When Breath Becomes Air",
    author: "Paul Kalanithi",
    year: 2016,
    read: "2023-11",
    rating: 4,
    tone: "#6aa0d8",
    tags: ["american", "memoir", "medicine", "grief"],
    review: [
      "maybe words will come to me later. such a heartbreaking read",
    ],
  },
];

/** "2024.09" */
export const readLabel = (b: Book) => b.read?.replace("-", ".");

/** Hue in degrees (0–360) of a book's tone, for sorting the shelf by colour. */
export function hue(hex: string) {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255);
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const d = max - min;
  if (d < 0.08) return 400 + (1 - max) * 100; // greys/whites sort to the end, light → dark
  const h = max === r ? ((g - b) / d) % 6 : max === g ? (b - r) / d + 2 : (r - g) / d + 4;
  return (h * 60 + 360) % 360;
}
